//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartPayment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMINISTRADOR
    {
        public string ADM_IDENTIDAD { get; set; }
        public string ADM_CORREO_ELECTRONICO { get; set; }
        public string ADM_CONTRASENNA { get; set; }
    }
}
