//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartPayment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHOFER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHOFER()
        {
            this.PAGOes = new HashSet<PAGO>();
        }
    
        public string CHO_IDENTIFICACION { get; set; }
        public string CHO_CORREO_ELECTRONICO { get; set; }
        public string CHO_CONTRASENNA { get; set; }
        public string CHO_NOMBRE { get; set; }
        public string CHO_PRIMER_APELLIDO { get; set; }
        public string CHO_SEGUNDO_APELLIDO { get; set; }
        public System.DateTime CHO_FECHA_NACIMIENTO { get; set; }
        public bool CHO_ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAGO> PAGOes { get; set; }
    }
}
