//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartPayment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE()
        {
            this.PAGOes = new HashSet<PAGO>();
        }
    
        public string CLI_IDENTIFICACION { get; set; }
        public string CLI_CORREO_ELECTRONICO { get; set; }
        public string CLI_CONTRASENNA { get; set; }
        public string CLI_NOMBRE { get; set; }
        public string CLI_PRIMER_APELLIDO { get; set; }
        public string CLI_SEGUNDO_APELLIDO { get; set; }
        public System.DateTime CLI_FECHA_NACIMIENTO { get; set; }
        public string CLI_METODO_PAGO { get; set; }
        public decimal CLI_MONEDERO { get; set; }
        public string CLI_TIPO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAGO> PAGOes { get; set; }
    }
}
