//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartPayment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO
    {
        public int PAG_ID { get; set; }
        public string PAG_IDENTIFICACION_CLIENTE { get; set; }
        public string PAG_IDENTIFICACION_CHOFER { get; set; }
        public int PAG_CODIGO_CTP_RUTA { get; set; }
        public System.DateTime PAG_FECHA { get; set; }
        public bool RECHAZADO { get; set; }
    
        public virtual CHOFER CHOFER { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual RUTA RUTA { get; set; }
    }
}
