//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartPayment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RUTA()
        {
            this.PAGOes = new HashSet<PAGO>();
        }
    
        public int RUT_CODIGO_CTP { get; set; }
        public string RUT_PROVINCIA { get; set; }
        public string RUT_CANTON { get; set; }
        public string RUT_NOMBRE { get; set; }
        public decimal RUT_COSTO { get; set; }
        public bool RUT_ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAGO> PAGOes { get; set; }
    }
}
